cutadaptMinLength: 50
cutadaptErrorRate: 0.2
vsearchMinQual: 10
vsearchMaxee: 0.5
vsearchMinovlen: 50
fitnessMinInputCountAny: 0
fitnessMinInputCountAll: 0
fitnessMinOutputCountAny: 0
fitnessMinOutputCountAll: 0
sequenceType: "noncoding"
retainedReplicates: "1,2,3"
transLibrary: "FALSE"
transLibraryReverseComplement: "FALSE"
maxSubstitutions: 3
cutadaptCommand: "--cutadapt5First TGGCTTTGGGAATCAGGGTGGATTT --cutadapt5Second ACATGCCCATCATACCCCAACTGCT"
extraCommandsWrap: ""
extraCommandsSteam: ""
wildTypeSequence: "GGTAATAGCAGAGGGGGTGGAGCTGGTTTGGGAAACAATCAAGGTAGTAATATGGGTGGTGGGATGAACTTTGGTGCGTTCAGCATTAATCCAGCCATGATGGCTGCCGCCCAGGCAGCACTACAG"
