mergeForwardReverse: TRUE
minOverlap: 50
maxOverlap: 74
minMergedLength: 126
maxMergedLength: 126
maxFracMismatchOverlap: 0.5
greedyOverlap: FALSE
revComplForward: FALSE
revComplReverse: TRUE
avePhredMinForward: 0
avePhredMinReverse: 0
variableNMaxForward: 0
variableNMaxReverse: 0
umiNMax: 0
nbrMutatedCodonsMaxForward: -1
nbrMutatedCodonsMaxReverse: -1
nbrMutatedBasesMaxForward: 3
nbrMutatedBasesMaxReverse: 0
forbiddenMutatedCodonsForward: ""
forbiddenMutatedCodonsReverse: ""
useTreeWTmatch: FALSE
mutatedPhredMinForward: 20
mutatedPhredMinReverse: 20
mutNameDelimiter: "."
constantMaxDistForward: -1
constantMaxDistReverse: -1
variableCollapseMaxDist: 0
variableCollapseMinReads: 0
variableCollapseMinRatio: 0
umiCollapseMaxDist: 0
filteredReadsFastqForward: ""
filteredReadsFastqReverse: ""
verbose: FALSE
chunkSize: 100000

countType: "reads"

minInputCountAny: 0
minInputCountAll: 0
minOutputCountAny: 0
minOutputCountAll: 0

collapseToAA: FALSE

replicateCol: "experiment"
conditionCol: "selection_id"
numerator: "1"
denominator: "0"
odCol: "OD"
wtrows: 
  - "f.0.NA"
  - "f.0.WT"
# fcMethod: "edgeR"
normMethod: "sum"
