cutadaptMinLength: 50
cutadaptErrorRate: 0.2
vsearchMinQual: 1
vsearchMaxee: 0.5
vsearchMinovlen: 10
fitnessMinInputCountAny: 0
fitnessMinInputCountAll: 0
fitnessMinOutputCountAny: 0
fitnessMinOutputCountAll: 0
sequenceType: "coding"
retainedReplicates: "1,2,3"
transLibrary: "TRUE"
transLibraryReverseComplement: "FALSE"
maxSubstitutions: 2
cutadaptCommand: "--cutadaptCut5First 11 --cutadaptCut5Second 9 --cutadapt5First AACCGGAGGAGGGAGCTG --cutadapt5Second GAAAAAGGAAGCTGGAGAGA"
extraCommandsWrap: "--mutagenesisType codon --permittedSequences NNBNNBNNVNNSNNVNNSNNSNNVNNSNNVNNVNNVNNBNNSNNSNNBNNBNNSNNSNNSNNSNNBNNSNNSNNSNNSNNSNNSNNSNNVNNVNNVNNSNNSNNSNNSNNSNNVNNVNNSNNVNNSNNSNNVNNBNNSNNSNNSNNSNNSNNSNNSNNSNNSNNSNNSNNSNNSNNVNNSNNSNNVNNSNNB"
extraCommandsSteam: ""
wildTypeSequence: "ACTGATACACTCCAAGCGGAGACAGACCAACTAGAAGATGAGAAGTCTGCTTTGCAGACCGAGATTGCCAACCTGCTGAAGGAGAAGGAAAAACTAATCGCCCGGCTGGAGGAAAAAGTGAAAACCTTGAAAGCTCAGAACTCGGAGCTGGCGTCCACGGCCAACATGCTCAGGGAACAGGTGGCACAGCTT"
